name: Create Endpoint and Deploy Model

on:
  workflow_dispatch:

jobs:
  DeployModel:
    runs-on: ubuntu-latest
    environment:
        name: Production
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Create model
      run: | 
        MODEL_NAME='sklearn-diabetes'
        az ml model create --name $MODEL_NAME --type "mlflow_model" --path "sklearn-diabetes/model" -w mlops-workspace-rt
      
    - name: Create a managed online endpoint
      run: |
        az ml online-endpoint create --name $ENDPOINT_NAME -f production/create-endpoint.yaml -g mlops-challenge -w mlops-workspace-rt
        
    - name: Create the deployment
      run: | 
        az ml online-deployment create --name sklearn-deployment --endpoint $ENDPOINT_NAME -f production/sklearn-deployment.yaml --all-traffic -g mlops-challenge -w mlops-workspace-rt
