name: Create Endpoint and Deploy Model

on:
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
        
    - name: Get the latest model version
      run: | 
        latest_version=$(az ml model list -n "your_model_name" -g "your_resource_group_name" --query '[].version' -o tsv)
        echo "Latest model version: $latest_version"
        echo "::set-output name=latest_version::$latest_version"
      
    - name: Deploy the latest model to an endpoint
      env:
        MODEL_VERSION: ${{ steps.get_latest_version.outputs.latest_version }}
      run: |
        az ml online-endpoint create --resource-group mlops-challenge --name MyEndpoint --model-name Production-Diabetes-Model:$MODEL_VERSION --query -o tsv
