name: Train Dev and Prod on Push to Main

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main 

jobs:
  trian_dev:
    runs-on: ubuntu-latest

    env:
      DATA_FOLDER: diabetes-dev-folder

    steps:
      - name: Checkout code
  train_prod:
     runs-on: ubuntu-latest

    env:
      DATA_FOLDER: diabetes-dev-folder

    steps:
      - name: Checkout code
  

jobs:
  my_first_job:
    name: My first job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: My first step
        uses: azure/actions/azureml@v1
        with:
          code: model
          command: >-
            python train.py
            --training_data ${{inputs.training_data}}
            --reg_rate ${{inputs.reg_rate}}
        inputs:
          training_data:
            type: uri_folder
            path: azureml:Diabetes-prod-folder:1
          reg_rate: 0.1
        env:
          name: Development
          url: https://github.com
        compute: aml_cluster
        experiment_name: train_diabetes_model
        description: Train the diabetes model.

  my_second_job:
    name: My second job
    $schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
    code: model
    command: >-
      python train.py
      --training_data ${{inputs.training_data}}
      --reg_rate ${{inputs.reg_rate}}
    inputs:
      training_data: 
        type: uri_folder 
        path: azureml:Diabetes-prod-folder:1
      reg_rate: 0.1
    environment:
        name: Production
        url: https://github.com
    compute: aml_cluster
    experiment_name: train_diabetes_model
    description: Train the diabetes model.
    

