name: Train on Prod and Dev

on:
  push:
    branches:
      - main

jobs:
  development:
    runs-on: ubuntu-latest
    environment: Development
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Use Python version 3.8
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'
    - name: Run Dev Training Script
      run: |
        $schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
        code: model
        command: >-
         python train.py
          --training_data ${{inputs.training_data}}
          --reg_rate ${{inputs.reg_rate}}
        inputs:
          training_data: 
            type: uri_folder 
            path: azureml:Diabetes-dev-folder:1
          reg_rate: 0.1
        environment: azureml:AzureML-sklearn-0.24-ubuntu18.04-py37-cpu@latest
        compute: aml_cluster
        experiment_name: diabetes_model
        description: Train the diabetes model.
  production:
    runs-on: ubuntu-latest
    environment: Production
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Use Python version 3.8
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'
    - name: Run Dev Training Script
      run: |
        $schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
        code: model
        command: >-
         python train.py
          --training_data ${{inputs.training_data}}
          --reg_rate ${{inputs.reg_rate}}
        inputs:
          training_data: 
            type: uri_folder 
            path: azureml:Diabetes-prod-folder:1
          reg_rate: 0.1
        environment: azureml:AzureML-sklearn-0.24-ubuntu18.04-py37-cpu@latest
        compute: aml_cluster
        experiment_name: diabetes_model
        description: Train the diabetes model.
